wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1706916471.129764
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 23
      - 35
      4: 3.11.5
      5: 0.16.2
      8:
      - 4
      - 5
      13: darwin-arm64
